name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: codx
            asset_name: codx-linux-amd64
          - os: windows-latest
            artifact_name: codx.exe
            asset_name: codx-windows-amd64.exe
          - os: macos-latest
            artifact_name: codx
            asset_name: codx-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --name codx --add-data "src/codx/core/schema.sql:codx/core" src/codx/__main__.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        cp codx-linux-amd64/codx release-assets/codx-linux-amd64
        cp codx-windows-amd64.exe/codx.exe release-assets/codx-windows-amd64.exe
        cp codx-macos-arm64/codx release-assets/codx-macos-arm64
        chmod +x release-assets/codx-*
        ls -la release-assets/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## Codx Snippet Manager ${{ github.ref_name }}
          
          A powerful command-line tool for managing and organizing code snippets with an interactive TUI.
          
          ### Features
          - 🔍 Smart search and filtering
          - 📝 Interactive TUI for browsing snippets
          - 🏷️ Tag-based organization
          - 🔄 Variable substitution
          - 📋 Clipboard integration
          - 🚀 Direct execution of snippets
          - 📦 Import/export functionality
          
          ### Installation
          
          **Option 1: Install from PyPI**
          ```bash
          pip install codx-snippet-manager
          ```
          
          **Option 2: Download standalone executable**
          Download the appropriate executable for your platform from the assets below.
          
          ### Quick Start
          ```bash
          # Initialize the database
          codx init
          
          # Add your first snippet
          codx add
          
          # Launch interactive finder
          codx find
          ```
          
          ### Assets
          - `codx-linux-amd64`: Linux x86_64 executable
          - `codx-windows-amd64.exe`: Windows x86_64 executable  
          - `codx-macos-arm64`: macOS ARM64 (Apple Silicon) executable
        draft: false
        prerelease: false
        files: release-assets/*